### ISSUE TITLE
Hello Calimero!

### ISSUE THREAD

**Issue by kevinjaypatel** [calimero-network/calimero-network.github.io#29]
Hello, my name is Kevin Patel. I am participating in the REDACT hackathon, and I just wanted to say hello! 

All the best, 
Kevin 😇

**Comment by chefsale** [comment]
Hi Kevin, nice to meet you. I hope you are interested in hacking on Calimero. Can we help somehow?

**Comment by MatejVukosav** [comment]
Hi @kevinjaypatel 

Glad to have you here. 

To keep our repos structured, I am closing the issue section. Let's use [discussions](https://github.com/orgs/calimero-network/discussions/categories/near-redacted) to see if we can help you with the hackathon project.
